#!/bin/bash
#test
source "${OPENSHIFT_RUBY_DIR}/lib/ruby_context"
pushd ${OPENSHIFT_REPO_DIR} 1> /dev/null
SAVED_GIT_DIR=$GIT_DIR
unset GIT_DIR
ruby_context "bundle install"
export GIT_DIR=$SAVED_GIT_DIR
popd 1> /dev/null

